title: Project
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
          -
            handle: name
            field:
              type: text
              display: Name
              instructions: 'The human readable name of the project. Eg. Laravel, Statamic, React'
          -
            handle: latest_stable_release
            field:
              max_items: 1
              create: false
              collections:
                - releases
              type: entries
              display: 'Latest stable release'
              instructions: 'The latest, stable release for this project.'
      -
        display: Logos
        instructions: "Set your projects' logos or adjust their settings."
        fields:
          -
            handle: logo
            field:
              container: assets
              type: assets
              display: Logo
              max_files: 1
              mode: grid
              dynamic: slug
              instructions: 'The default logo for this project. SVG is the recommended format.'
          -
            handle: logo_dark
            field:
              container: assets
              type: assets
              display: 'Dark logo'
              instructions: 'The logo for this project when the theme is dark. SVG is the recommended format.'
              max_files: 1
              mode: grid
              dynamic: slug
          -
            handle: logo_text
            field:
              placeholder: 'Your project'
              character_limit: 20
              type: textarea
              display: 'Logo text'
              instructions: 'If no logos are set, the logo for the project will default to this text. HTML & Antlers is allowed.'
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
